
trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
        conda create -y -n n88 python=3 boost
        source activate n88
    displayName: Setup conda
  - script: |
      mkdir build
    displayName: Make Build Directories
  - task: CMake@1
    inputs:
        workingDirectory: 'build'
        cmakeArgs: '..'

- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - script: echo macOS

- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - script: echo Windows
