
trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - bash: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo apt -y update
        sudo apt-get install libboost-all-dev ninja-build libgtest-dev -y
    displayName: apt-get
  - script: |
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp *.a /usr/lib
    displayName: GTEST hot fix
  - script: |
      mkdir build
    displayName: Make Build Directories
  - task: CMake@1
    inputs:
        workingDirectory: 'build'
        cmakeArgs: '-GNinja -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTING:BOOL=ON ..'
  - script: |
      cd build
      ninja
      ctest -V
    displayName: Make and CTest

- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH
  - script: |
        conda create -y -n n88 python=3 boost
        source activate n88
    displayName: Setup conda

- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - script: echo Windows
