
trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      mkdir build
      cd build
      ccmake ..
      make
      ctest -V
  displayName: Build and test

- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - script: echo Mac

- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - script: echo Windows
