
trigger:
- master

jobs:
- job: Linux
  displayName: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      mkdir build
      cd build
      ccmake ..
      make
      ctest -V

- job: macOS
  displayName: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - script: |
      mkdir build
      cd build
      ccmake ..
      make
      ctest -V

- job: Windows
  displayName: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - script: echo Windows
