
trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - bash: |
        echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to path, change permissions
  - script: |
        conda create -y -n n88 python=3 conda-build
    displayName: Setup conda
  - script: |
        source activate n88
        conda-build conda-recipe/n88util/
    displayName: Conda build
  - task: CopyFiles@2
    inputs:
        sourceFolder: /usr/share/miniconda/envs/n88/conda-bld/linux-64/
        contents: '*.tar.bz2'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: Copy conda build
  - task: PublishBuildArtifacts@1
    inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: n88util-Linux
    displayName: Publish artifact

- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - bash: |
        echo "##vso[task.prependpath]$CONDA/bin"
        sudo chown -R $USER $CONDA
    displayName: Add conda to path
  - script: |
        conda create -y -n n88 python=3 conda-build
    displayName: Setup conda
  - script: |
        source activate n88
        conda-build conda-recipe/n88util/
    displayName: Conda build
  - task: CopyFiles@2
    inputs:
        sourceFolder: /usr/local/miniconda/envs/n88/conda-bld/osx-64/
        contents: '*.tar.bz2'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: Copy conda build
  - task: PublishBuildArtifacts@1
    inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: n88util-macOS
    displayName: Publish artifact

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - powershell: |
        Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to path
  - script: |
        conda create -y -n n88 python=3 conda-build
    displayName: Setup conda
  - script: |
        call activate n88
        conda-build conda-recipe/n88util/
    displayName: Conda build
  - task: CopyFiles@2
    inputs:
        sourceFolder: /usr/local/miniconda/envs/n88/conda-bld/osx-64/
        contents: '*.tar.bz2'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: Copy conda build
  - task: PublishBuildArtifacts@1
    inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: n88util-Windows
    displayName: Publish artifact
