
trigger:
- master

jobs:
- job: Linux
  displayName: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      mkdir build
    displayName: Make Build Directories
  - task: CMake@1
    inputs:
        workingDirectory: 'build'

- job: macOS
  displayName: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - script: echo macOS

- job: Windows
  displayName: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - script: echo Windows
