
trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - bash: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo apt -y update
        sudo apt-get install libboost-all-dev -y
    displayName: Install boost
  - script: |
      mkdir build
    displayName: Make Build Directories
  - task: CMake@1
    inputs:
        workingDirectory: 'build'
        cmakeArgs: '..'

- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - script: echo macOS

- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - script: echo Windows
